version: "3.8"

services:
  user_service:
    container_name: user_service
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      mariadb-node1:
        condition: service_healthy
      mariadb-node2:
        condition: service_healthy
      redis:
        condition: service_healthy


  report_service:
    container_name: report_service
    build:
      context: ./report_service
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    depends_on:
      mariadb-node1:
        condition: service_healthy
      mariadb-node2:
        condition: service_healthy

  conference_service:
    container_name: conference_service
    build:
      context: ./conference_service
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    depends_on:
      mariadb-node1:
        condition: service_healthy
      mariadb-node2:
        condition: service_healthy

  mariadb-node1:
    container_name: mariadb-node1
    image: mariadb:10.7
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/1:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=database
    healthcheck:
      test: "/usr/bin/mariadb --user=user --password=password --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 1s
      retries: 15

  mariadb-node2:
    container_name: mariadb-node2
    image: mariadb:10.7
    ports:
      - "3316:3306"
    volumes:
      - ./mariadb/2:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=database
    healthcheck:
      test: "/usr/bin/mariadb --user=user --password=password --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 1s
      retries: 15

  redis:
    container_name: redis
    image: redis:7.2.3
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30